
namespace RagBackend.Domain.Models
{
    /// <summary>
    /// Response model returned from the backend to the chat user interface.
    /// 
    /// This class represents a single assistant response in the chat,
    /// including the answer text, any supporting context, and flags
    /// that tell the UI how to display the message.
    /// </summary>
    public sealed class ChatMessageResponse
    {
        /// <summary>
        /// The text reply generated by the assistant.
        /// 
        /// This may be:
        /// - an actual answer
        /// - a clarification request
        /// - or a fallback message such as "I don't know"
        /// </summary>
        public string Reply { get; set; } = string.Empty;

        /// <summary>
        /// The list of document chunks that were used to generate the answer.
        /// 
        /// This allows the UI to display supporting context and
        /// helps make the system more transparent.
        /// </summary>
        public List<string> Context { get; set; } = new();

        /// <summary>
        /// Indicates whether this response is a fallback rather than a direct answer.
        /// 
        /// Examples:
        /// - true when no relevant context was found
        /// - true when the system asks for clarification
        /// </summary>
        public bool IsFallback { get; set; }

        /// <summary>
        /// Indicates whether the user needs to clarify their question.
        /// 
        /// This is used by the UI to distinguish between:
        /// - "I don't know" responses
        /// - and requests for more specific input
        /// </summary>
        public bool NeedsClarification { get; set; }
    }
}